/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

/**
 *
 * @author JOEL
 */
public class FormPersona extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtAppNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        PanelBtnMain = new javax.swing.JPanel();
        BtnNuevo = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePersona = new javax.swing.JTable();
        PanelBtnSecond = new javax.swing.JPanel();
        BtnEdit = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));
        PanelDatos.setLayout(null);

        jLabel1.setText("Apellidos y nombres:");
        PanelDatos.add(jLabel1);
        jLabel1.setBounds(10, 20, 100, 20);
        PanelDatos.add(TxtAppNombres);
        TxtAppNombres.setBounds(120, 20, 190, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("DNI:");
        PanelDatos.add(jLabel2);
        jLabel2.setBounds(10, 50, 100, 20);
        PanelDatos.add(TxtDni);
        TxtDni.setBounds(120, 50, 100, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Telefono:");
        PanelDatos.add(jLabel3);
        jLabel3.setBounds(10, 80, 100, 14);
        PanelDatos.add(TxtTelefono);
        TxtTelefono.setBounds(120, 80, 100, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Dirección:");
        PanelDatos.add(jLabel4);
        jLabel4.setBounds(10, 110, 100, 14);
        PanelDatos.add(TxtDireccion);
        TxtDireccion.setBounds(120, 110, 190, 20);

        getContentPane().add(PanelDatos);
        PanelDatos.setBounds(0, 50, 440, 140);

        PanelBtnMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelBtnMain.setLayout(null);

        BtnNuevo.setIcon(new javax.swing.ImageIcon("D:\\Proyectos Programacion\\Desarrollo de Software Amidata\\amipro\\amipro\\src\\resources\\nuevo16.png")); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.setBorderPainted(false);
        BtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnNuevo.setIconTextGap(6);
        BtnNuevo.setVerifyInputWhenFocusTarget(false);
        PanelBtnMain.add(BtnNuevo);
        BtnNuevo.setBounds(10, 10, 90, 20);

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        PanelBtnMain.add(BtnGuardar);
        BtnGuardar.setBounds(110, 10, 90, 20);

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        PanelBtnMain.add(BtnCancelar);
        BtnCancelar.setBounds(220, 10, 90, 20);

        getContentPane().add(PanelBtnMain);
        PanelBtnMain.setBounds(0, 10, 440, 40);

        TablePersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablePersona);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 220, 440, 100);

        PanelBtnSecond.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelBtnSecond.setLayout(null);

        BtnEdit.setText("Editar");
        PanelBtnSecond.add(BtnEdit);
        BtnEdit.setBounds(10, 3, 73, 23);

        BtnEliminar.setText("Eliminar");
        PanelBtnSecond.add(BtnEliminar);
        BtnEliminar.setBounds(90, 3, 73, 23);

        getContentPane().add(PanelBtnSecond);
        PanelBtnSecond.setBounds(0, 190, 440, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JPanel PanelBtnMain;
    private javax.swing.JPanel PanelBtnSecond;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JTable TablePersona;
    private javax.swing.JTextField TxtAppNombres;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtDni;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
